### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by OlafurTorfi**
update dependencies

fix format scripts to exclude ./test/sql folder

format using new prettier version.

patch update

### CODE REVIEW

**Review by bergur — APPROVED** [review]

**Comment by coinnect-project** [comment]
hi, after you released version 4.2.1 I get this error when updating/istalling the library

npm WARN tarball tarball data for node-jt400@https://registry.npmjs.org/node-jt400/-/node-jt400-4.2.1.tgz (sha512-kkZNxU0H//mGcihqqIKJZTG+rrQlpXmi//WK3XkmOBv0RAMlU+utuM8dPyA2HkY/x+GA3QlbRWr2ljSjmdzJjg==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for node-jt400@https://registry.npmjs.org/node-jt400/-/node-jt400-4.2.1.tgz (sha512-kkZNxU0H//mGcihqqIKJZTG+rrQlpXmi//WK3XkmOBv0RAMlU+utuM8dPyA2HkY/x+GA3QlbRWr2ljSjmdzJjg==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-kkZNxU0H//mGcihqqIKJZTG+rrQlpXmi//WK3XkmOBv0RAMlU+utuM8dPyA2HkY/x+GA3QlbRWr2ljSjmdzJjg== integrity checksum failed when using sha512: wanted sha512-kkZNxU0H//mGcihqqIKJZTG+rrQlpXmi//WK3XkmOBv0RAMlU+utuM8dPyA2HkY/x+GA3QlbRWr2ljSjmdzJjg== but got sha512-khfwfWiTuk6DxlEKcbcEqHvwDsBnniDlUHhc0jxa32BdEh+A8m2L+aB3O8I4mFUHqSnLGUH0yNGb3vl9OIjarQ==. (5864209 bytes)

**Comment by OlafurTorfi** [comment]
Hi. That's interesting. We were having some issues with the build pipe, it looks like somehow two different versions got deployed with the same semver number. Although I thought that shouldn't be able to happen.

If you try removing your node_modules folder and run `npm install` again, I think it should work. I am having not able to replicate the issue on my machine.

We have also just released version 4.3.0, which adds a `trim` query option, that lets you control whether your query result strings are trimmed or not (they are trimmed by default).

**Comment by OlafurTorfi** [comment]
Hi @coinnect-project 
I'm having some trouble running the `should insert blob` test. The Blob length comes out far longer when reading it from the database.
Is the test working for you?

**Comment by coinnect-project** [comment]
Sorry I didn't try it I dont have a local test as400, I copied the clob test but now I realize that it's not possible to test. From as400 you will get the blob type (which should kind of an array of bytes) while you have the base64 string so it can't be compared.
Actually to verify that insert worked I made an insert then I asked customer as400 technician to retrieve back the field and write as a jpg file and send it to me. It was the correct image. I don't know how to write as a file from blob column, maybe doing some conversion in test method it is possibile to compare but it's not like the clob, you should view what you wrote to know if it's correct; because the length could be the same but file results corrupted or something

**Pull request merged**
