### PR TITLE
Single cmd

### PR DESCRIPTION
**Pull request by ChrisKader**

### CODE REVIEW

**Comment by ChrisKader** [comment]
Any updates on the PR?

**Comment by cwg999** [comment]
The maintainer's aren't the quickest to respond, but when they do they'll likely want you to add in a test, for example: https://github.com/tryggingamidstodin/node-jt400/blob/master/test/dataq-spec.ts --- make it generic enough that it could run on any AS400 system, i.e. not including that specific library

Otherwise looks like a good PR!

**Comment by cwg999** [comment]
Also, side note, if you want to utilize your own fork for your node-js package you can do something like `"node-jt400": "git+https://github.com/cwg999/node-jt400.git#msgq3"` in your package.json where the hash is the tag of the specific commit you wish to use.

**Comment by bergur** [comment]
Hi Chris and sorry for the late reply. Haven't been at work for few of last days. Will take a look and let you know.

**Comment by ChrisKader** [comment]
Thank you @cwg999. I am going to make the proper improvements now.

**Comment by bergur** [comment]
Also, some tests are TM specific if I remember correctly. You don't have to make sure all tests run, just the ones you're adding.

**Pull request closed without merging**
